fields:
  ## name
  clan:
    label: "clan"
    input: select
    options:
      SELECT: SELECT
      Drenchen: Drenchen
      Dousan: Dousan
      Grottan: Grottan
      Sifa: Sifa
      Spriton: Spriton
      Stonewood: Stonewood
      Vapra: Vapra
  portrait:
    label: "portrait"
    input: integer
  last:
    label: "last"
    input: string
  xp:
    label: "xp"
    input: string
  health:
    label: "health"
    input: string
  ### traits
  trait 01:
    label: "trait 01"
    input: string
  trait effect 01:
    label: "trait effect 01"
    input: string
  trait 02:
    label: "trait 02"
    input: string
  trait effect 02:
    label: "trait effect 02"
    input: string
  trait 03:
    label: "trait 03"
    input: string
  trait effect 03:
    label: "trait effect 03"
    input: string
  trait 04:
    label: "trait 04"
    input: string
  trait effect 04:
    label: "trait effect 04"
    input: string
  trait 05:
    label: "trait 05"
    input: string
  trait effect 05:
    label: "trait effect 05"
    input: string
  trait 06:
    label: "trait 06"
    input: string
  trait effect 06:
    label: "trait effect 06"
    input: string
  trait 07:
    label: "trait 07"
    input: string
  trait effect 07:
    label: "trait effect 07"
    input: string
  ### notes
  notes:
    label: notes
    input: text
    rows: 3
  ### flaws
  flaw 01:
    label: "flaw 01"
    input: string
  flaw 02:
    label: "flaw 02"
    input: string
  flaw 03:
    label: "flaw 03"
    input: string
  flaw 04:
    label: "flaw 04"
    input: string
  flaw 05:
    label: "flaw 05"
    input: string
  flaw 06:
    label: "flaw 06"
    input: string
  flaw 07:
    label: "flaw 07"
    input: string
  ### gear
  gear name 01:
    label: "gear name 01"
    input: string
  gear skill 01:
    label: "gear skill 01"
    input: string
  gear durability 01:
    label: "gear durability 01"
    input: string
  gear effect 01:
    label: "gear effect 01"
    input: string
  gear keywords 01:
    label: "gear keywords 01"
    input: string
  gear name 02:
    label: "gear name 02"
    input: string
  gear skill 02:
    label: "gear skill 02"
    input: string
  gear durability 02:
    label: "gear durability 02"
    input: string
  gear effect 02:
    label: "gear effect 02"
    input: string
  gear keywords 02:
    label: "gear keywords 02"
    input: string
  gear name 03:
    label: "gear name 03"
    input: string
  gear skill 03:
    label: "gear skill 03"
    input: string
  gear durability 03:
    label: "gear durability 03"
    input: string
  gear effect 03:
    label: "gear effect 03"
    input: string
  gear keywords 03:
    label: "gear keywords 03"
    input: string
  gear name 04:
    label: "gear name 04"
    input: string
  gear skill 04:
    label: "gear skill 04"
    input: string
  gear durability 04:
    label: "gear durability 04"
    input: string
  gear effect 04:
    label: "gear effect 04"
    input: string
  gear keywords 04:
    label: "gear keywords 04"
    input: string
  gear name 05:
    label: "gear name 05"
    input: string
  gear skill 05:
    label: "gear skill 05"
    input: string
  gear durability 05:
    label: "gear durability 05"
    input: string
  gear effect 05:
    label: "gear effect 05"
    input: string
  gear keywords 05:
    label: "gear keywords 05"
    input: string
  gear name 06:
    label: "gear name 06"
    input: string
  gear skill 06:
    label: "gear skill 06"
    input: string
  gear durability 06:
    label: "gear durability 06"
    input: string
  gear effect 06:
    label: "gear effect 06"
    input: string
  gear keywords 06:
    label: "gear keywords 06"
    input: string
  ### skills
  skill 01:
    label: "skill 01"
    input: checkbox
  skill 02:
    label: "skill 02"
    input: checkbox
  skill 03:
    label: "skill 03"
    input: checkbox
  skill 04:
    label: "skill 04"
    input: checkbox
  skill 05:
    label: "skill 05"
    input: checkbox
  skill 06:
    label: "skill 06"
    input: checkbox
  skill 07:
    label: "skill 07"
    input: checkbox
  ### specialisations
  spec 01:
    label: "spec 01"
    input: checkbox
  master 01:
    label: "master 01"
    input: checkbox
  spec 02:
    label: "spec 02"
    input: checkbox
  master 02:
    label: "master 02"
    input: checkbox
  spec 03:
    label: "spec 03"
    input: checkbox
  master 03:
    label: "master 03"
    input: checkbox
  spec 04:
    label: "spec 04"
    input: checkbox
  master 04:
    label: "master 04"
    input: checkbox
  spec 05:
    label: "spec 05"
    input: checkbox
  master 05:
    label: "master 05"
    input: checkbox
  spec 06:
    label: "spec 06"
    input: checkbox
  master 06:
    label: "master 06"
    input: checkbox
  spec 07:
    label: "spec 07"
    input: checkbox
  master 07:
    label: "master 07"
    input: checkbox
  spec 08:
    label: "spec 08"
    input: checkbox
  master 08:
    label: "master 08"
    input: checkbox
  spec 09:
    label: "spec 09"
    input: checkbox
  master 09:
    label: "master 09"
    input: checkbox
  spec 10:
    label: "spec 10"
    input: checkbox
  master 10:
    label: "master 10"
    input: checkbox
  spec 11:
    label: "spec 11"
    input: checkbox
  master 11:
    label: "master 11"
    input: checkbox
  spec 12:
    label: "spec 12"
    input: checkbox
  master 12:
    label: "master 12"
    input: checkbox
  spec 13:
    label: "spec 13"
    input: checkbox
  master 13:
    label: "master 13"
    input: checkbox
  spec 14:
    label: "spec 14"
    input: checkbox
  master 14:
    label: "master 14"
    input: checkbox
  spec 15:
    label: "spec 15"
    input: checkbox
  master 15:
    label: "master 15"
    input: checkbox
  spec 16:
    label: "spec 16"
    input: checkbox
  master 16:
    label: "master 16"
    input: checkbox
  spec 17:
    label: "spec 17"
    input: checkbox
  master 17:
    label: "master 17"
    input: checkbox
  spec 18:
    label: "spec 18"
    input: checkbox
  master 18:
    label: "master 18"
    input: checkbox
  spec 19:
    label: "spec 19"
    input: checkbox
  master 19:
    label: "master 19"
    input: checkbox
  spec 20:
    label: "spec 20"
    input: checkbox
  master 20:
    label: "master 20"
    input: checkbox
  spec 21:
    label: "spec 21"
    input: checkbox
  master 21:
    label: "master 21"
    input: checkbox