fields:
  name:
    label: "name"
    input: string
  keywords:
    label: "keywords"
    input: string
  level:
    label: "level"
    input: string
  xp:
    label: "xp"
    input: string
  description:
    label: "description"
    input: text
    rows: 3
  imageid:
    label: "imageid"
    input: string
  ctype:
    label: "ctype"
    input: select
    options:
      normal: normal
      mighty: mighty
      legendary: legendary
      notable: notable
      major: major
  att strength:
    label: "att strength"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  att perception:
    label: "att perception"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  att endurance:
    label: "att endurance"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  att charisma:
    label: "att charisma"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  att intelligence:
    label: "att intelligence"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  att agility:
    label: "att agility"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  att luck:
    label: "att luck"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  skill name 01:
    label: "skill name 01"
    input: string
  skill rank 01:
    label: "skill rank 01"
    input: string
  skill tag 01:
    label: "skill tag 01"
    input: checkbox
  skill name 02:
    label: "skill name 02"
    input: string
  skill rank 02:
    label: "skill rank 02"
    input: string
  skill tag 02:
    label: "skill tag 02"
    input: checkbox
  skill name 03:
    label: "skill name 03"
    input: string
  skill rank 03:
    label: "skill rank 03"
    input: string
  skill tag 03:
    label: "skill tag 03"
    input: checkbox
  skill name 04:
    label: "skill name 04"
    input: string
  skill rank 04:
    label: "skill rank 04"
    input: string
  skill tag 04:
    label: "skill tag 04"
    input: checkbox
  skill name 05:
    label: "skill name 05"
    input: string
  skill rank 05:
    label: "skill rank 05"
    input: string
  skill tag 05:
    label: "skill tag 05"
    input: checkbox
  skill name 06:
    label: "skill name 06"
    input: string
  skill rank 06:
    label: "skill rank 06"
    input: string
  skill tag 06:
    label: "skill tag 06"
    input: checkbox
  skill name 07:
    label: "skill name 07"
    input: string
  skill rank 07:
    label: "skill rank 07"
    input: string
  skill tag 07:
    label: "skill tag 07"
    input: checkbox
  skill name 08:
    label: "skill name 08"
    input: string
  skill rank 08:
    label: "skill rank 08"
    input: string
  skill tag 08:
    label: "skill tag 08"
    input: checkbox
  skill name 09:
    label: "skill name 09"
    input: string
  skill rank 09:
    label: "skill rank 09"
    input: string
  skill tag 09:
    label: "skill tag 09"
    input: checkbox
  skill name 10:
    label: "skill name 10"
    input: string
  skill rank 10:
    label: "skill rank 10"
    input: string
  skill tag 10:
    label: "skill tag 10"
    input: checkbox
  skill name 11:
    label: "skill name 11"
    input: string
  skill rank 11:
    label: "skill rank 11"
    input: string
  skill tag 11:
    label: "skill tag 11"
    input: checkbox
  skill name 12:
    label: "skill name 12"
    input: string
  skill rank 12:
    label: "skill rank 12"
    input: string
  skill tag 12:
    label: "skill tag 12"
    input: checkbox
  skill name 13:
    label: "skill name 13"
    input: string
  skill rank 13:
    label: "skill rank 13"
    input: string
  skill tag 13:
    label: "skill tag 13"
    input: checkbox
  skill name 14:
    label: "skill name 14"
    input: string
  skill rank 14:
    label: "skill rank 14"
    input: string
  skill tag 14:
    label: "skill tag 14"
    input: checkbox
  skill name 15:
    label: "skill name 15"
    input: string
  skill rank 15:
    label: "skill rank 15"
    input: string
  skill tag 15:
    label: "skill tag 15"
    input: checkbox
  skill name 16:
    label: "skill name 16"
    input: string
  skill rank 16:
    label: "skill rank 16"
    input: string
  skill tag 16:
    label: "skill tag 16"
    input: checkbox
  skill name 17:
    label: "skill name 17"
    input: string
  skill rank 17:
    label: "skill rank 17"
    input: string
  skill tag 17:
    label: "skill tag 17"
    input: checkbox
  skill name 18:
    label: "skill name 18"
    input: string
  skill rank 18:
    label: "skill rank 18"
    input: string
  skill tag 18:
    label: "skill tag 18"
    input: checkbox
  skill name 19:
    label: "skill name 19"
    input: string
  skill rank 19:
    label: "skill rank 19"
    input: string
  skill tag 19:
    label: "skill tag 19"
    input: checkbox
  skill name 20:
    label: "skill name 20"
    input: string
  skill rank 20:
    label: "skill rank 20"
    input: string
  skill tag 20:
    label: "skill tag 20"
    input: checkbox
  defense:
    label: "defense"
    input: string
  initiative:
    label: "initiative"
    input: string
  health:
    label: "health"
    input: string
  dr physical:
    label: "dr physical"
    input: string
  dr energy:
    label: "dr energy"
    input: string
  dr radiation:
    label: "dr radiation"
    input: string
  dr poison:
    label: "dr poison"
    input: string
  attacks:
    label: "attacks"
    input: text
    rows: 3
  spec abilities:
    label: "spec abilities"
    input: text
    rows: 3
  inventory:
    label: "inventory"
    input: text
    rows: 3