fields:
  name:
    label: "name"
    input: string
  class:
    label: "class"
    input: string
  imageid:
    label: "imageid"
    input: integer
  level:
    label: "level"
    input: string
  xp:
    label: "xp"
    input: string
  look:
    label: "look"
    input: text
    rows: 3
  armor:
    label: "armor"
    input: string
  hitpoints curr:
    label: "hitpoints curr"
    input: string
  hitpoints max:
    label: "hitpoints max"
    input: string
  damage:
    label: "damage"
    input: string
  alignment:
    label: "alignment"
    input: text
    rows: 3
  bonds:
    label: "bonds"
    input: text
    rows: 3
  race:
    label: "race"
    input: text
    rows: 3
  coin:
    label: "coin"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 3
  strength:
    label: "strength"
    input: string
  strength pen:
    label: "strength pen"
    input: checkbox
  dexterity:
    label: "dexterity"
    input: string
  dexterity pen:
    label: "dexterity pen"
    input: checkbox
  constitution:
    label: "constitution"
    input: string
  constitution pen:
    label: "constitution pen"
    input: checkbox
  intelligence:
    label: "intelligence"
    input: string
  intelligence pen:
    label: "intelligence pen"
    input: checkbox
  wisdom:
    label: "wisdom"
    input: string
  wisdom pen:
    label: "wisdom pen"
    input: checkbox
  charisma:
    label: "charisma"
    input: string
  charisma pen:
    label: "charisma pen"
    input: checkbox
### gear
  gear name 01:
    label: "gear name 01"
    input: string
  gear count 01:
    label: "gear count 01"
    input: string
  gear weight 01:
    label: "gear weight 01"
    input: string
  gear name 02:
    label: "gear name 02"
    input: string
  gear count 02:
    label: "gear count 02"
    input: string
  gear weight 02:
    label: "gear weight 02"
    input: string
  gear name 03:
    label: "gear name 03"
    input: string
  gear count 03:
    label: "gear count 03"
    input: string
  gear weight 03:
    label: "gear weight 03"
    input: string
  gear name 04:
    label: "gear name 04"
    input: string
  gear count 04:
    label: "gear count 04"
    input: string
  gear weight 04:
    label: "gear weight 04"
    input: string
  gear name 05:
    label: "gear name 05"
    input: string
  gear count 05:
    label: "gear count 05"
    input: string
  gear weight 05:
    label: "gear weight 05"
    input: string
  gear name 06:
    label: "gear name 06"
    input: string
  gear count 06:
    label: "gear count 06"
    input: string
  gear weight 06:
    label: "gear weight 06"
    input: string
  gear name 07:
    label: "gear name 07"
    input: string
  gear count 07:
    label: "gear count 07"
    input: string
  gear weight 07:
    label: "gear weight 07"
    input: string
  gear name 08:
    label: "gear name 08"
    input: string
  gear count 08:
    label: "gear count 08"
    input: string
  gear weight 08:
    label: "gear weight 08"
    input: string
  gear name 09:
    label: "gear name 09"
    input: string
  gear count 09:
    label: "gear count 09"
    input: string
  gear weight 09:
    label: "gear weight 09"
    input: string
  gear name 10:
    label: "gear name 10"
    input: string
  gear count 10:
    label: "gear count 10"
    input: string
  gear weight 10:
    label: "gear weight 10"
    input: string
  gear name 11:
    label: "gear name 11"
    input: string
  gear count 11:
    label: "gear count 11"
    input: string
  gear weight 11:
    label: "gear weight 11"
    input: string
  gear name 12:
    label: "gear name 12"
    input: string
  gear count 12:
    label: "gear count 12"
    input: string
  gear weight 12:
    label: "gear weight 12"
    input: string
  gear name 13:
    label: "gear name 13"
    input: string
  gear count 13:
    label: "gear count 13"
    input: string
  gear weight 13:
    label: "gear weight 13"
    input: string
  gear name 14:
    label: "gear name 14"
    input: string
  gear count 14:
    label: "gear count 14"
    input: string
  gear weight 14:
    label: "gear weight 14"
    input: string
  gear name 15:
    label: "gear name 15"
    input: string
  gear count 15:
    label: "gear count 15"
    input: string
  gear weight 15:
    label: "gear weight 15"
    input: string
  gear name 16:
    label: "gear name 16"
    input: string
  gear count 16:
    label: "gear count 16"
    input: string
  gear weight 16:
    label: "gear weight 16"
    input: string
  gear name 17:
    label: "gear name 17"
    input: string
  gear count 17:
    label: "gear count 17"
    input: string
  gear weight 17:
    label: "gear weight 17"
    input: string
  gear name 18:
    label: "gear name 18"
    input: string
  gear count 18:
    label: "gear count 18"
    input: string
  gear weight 18:
    label: "gear weight 18"
    input: string
  gear name 19:
    label: "gear name 19"
    input: string
  gear count 19:
    label: "gear count 19"
    input: string
  gear weight 19:
    label: "gear weight 19"
    input: string
  gear name 20:
    label: "gear name 20"
    input: string
  gear count 20:
    label: "gear count 20"
    input: string
  gear weight 20:
    label: "gear weight 20"
    input: string
  gear name 21:
    label: "gear name 21"
    input: string
  gear count 21:
    label: "gear count 21"
    input: string
  gear weight 21:
    label: "gear weight 21"
    input: string
  gear name 22:
    label: "gear name 22"
    input: string
  gear count 22:
    label: "gear count 22"
    input: string
  gear weight 22:
    label: "gear weight 22"
    input: string
  gear name 23:
    label: "gear name 23"
    input: string
  gear count 23:
    label: "gear count 23"
    input: string
  gear weight 23:
    label: "gear weight 23"
    input: string
  gear name 24:
    label: "gear name 24"
    input: string
  gear count 24:
    label: "gear count 24"
    input: string
  gear weight 24:
    label: "gear weight 24"
    input: string
  gear name 25:
    label: "gear name 25"
    input: string
  gear count 25:
    label: "gear count 25"
    input: string
  gear weight 25:
    label: "gear weight 25"
    input: string
  gear name 26:
    label: "gear name 26"
    input: string
  gear count 26:
    label: "gear count 26"
    input: string
  gear weight 26:
    label: "gear weight 26"
    input: string
  gear name 27:
    label: "gear name 27"
    input: string
  gear count 27:
    label: "gear count 27"
    input: string
  gear weight 27:
    label: "gear weight 27"
    input: string
  gear name 28:
    label: "gear name 28"
    input: string
  gear count 28:
    label: "gear count 28"
    input: string
  gear weight 28:
    label: "gear weight 28"
    input: string
  gear name 29:
    label: "gear name 29"
    input: string
  gear count 29:
    label: "gear count 29"
    input: string
  gear weight 29:
    label: "gear weight 29"
    input: string
  gear name 30:
    label: "gear name 30"
    input: string
  gear count 30:
    label: "gear count 30"
    input: string
  gear weight 30:
    label: "gear weight 30"
    input: string
### moves
  move name 01:
    label: "move name 01"
    input: string
  move details 01:
    label: "move details 01"
    input: text
    rows: 3
  move name 02:
    label: "move name 02"
    input: string
  move details 02:
    label: "move details 02"
    input: text
    rows: 3
  move name 03:
    label: "move name 03"
    input: string
  move details 03:
    label: "move details 03"
    input: text
    rows: 3
  move name 04:
    label: "move name 04"
    input: string
  move details 04:
    label: "move details 04"
    input: text
    rows: 3
  move name 05:
    label: "move name 05"
    input: string
  move details 05:
    label: "move details 05"
    input: text
    rows: 3
  move name 06:
    label: "move name 06"
    input: string
  move details 06:
    label: "move details 06"
    input: text
    rows: 3
  move name 07:
    label: "move name 07"
    input: string
  move details 07:
    label: "move details 07"
    input: text
    rows: 3
  move name 08:
    label: "move name 08"
    input: string
  move details 08:
    label: "move details 08"
    input: text
    rows: 3
  move name 09:
    label: "move name 09"
    input: string
  move details 09:
    label: "move details 09"
    input: text
    rows: 3
  move name 10:
    label: "move name 10"
    input: string
  move details 10:
    label: "move details 10"
    input: text
    rows: 3
  move name 11:
    label: "move name 11"
    input: string
  move details 11:
    label: "move details 11"
    input: text
    rows: 3
  move name 12:
    label: "move name 12"
    input: string
  move details 12:
    label: "move details 12"
    input: text
    rows: 3
  move name 13:
    label: "move name 13"
    input: string
  move details 13:
    label: "move details 13"
    input: text
    rows: 3
  move name 14:
    label: "move name 14"
    input: string
  move details 14:
    label: "move details 14"
    input: text
    rows: 3
  move name 15:
    label: "move name 15"
    input: string
  move details 15:
    label: "move details 15"
    input: text
    rows: 3
  move name 16:
    label: "move name 16"
    input: string
  move details 16:
    label: "move details 16"
    input: text
    rows: 3
  move name 17:
    label: "move name 17"
    input: string
  move details 17:
    label: "move details 17"
    input: text
    rows: 3
  move name 18:
    label: "move name 18"
    input: string
  move details 18:
    label: "move details 18"
    input: text
    rows: 3
  move name 19:
    label: "move name 19"
    input: string
  move details 19:
    label: "move details 19"
    input: text
    rows: 3
  move name 20:
    label: "move name 20"
    input: string
  move details 20:
    label: "move details 20"
    input: text
    rows: 3
  move name 21:
    label: "move name 21"
    input: string
  move details 21:
    label: "move details 21"
    input: text
    rows: 3
  move name 22:
    label: "move name 22"
    input: string
  move details 22:
    label: "move details 22"
    input: text
    rows: 3
  move name 23:
    label: "move name 23"
    input: string
  move details 23:
    label: "move details 23"
    input: text
    rows: 3
  move name 24:
    label: "move name 24"
    input: string
  move details 24:
    label: "move details 24"
    input: text
    rows: 3
  move name 25:
    label: "move name 25"
    input: string
  move details 25:
    label: "move details 25"
    input: text
    rows: 3
  move name 26:
    label: "move name 26"
    input: string
  move details 26:
    label: "move details 26"
    input: text
    rows: 3
  move name 27:
    label: "move name 27"
    input: string
  move details 27:
    label: "move details 27"
    input: text
    rows: 3
  move name 28:
    label: "move name 28"
    input: string
  move details 28:
    label: "move details 28"
    input: text
    rows: 3
  move name 29:
    label: "move name 29"
    input: string
  move details 29:
    label: "move details 29"
    input: text
    rows: 3
  move name 30:
    label: "move name 30"
    input: string
  move details 30:
    label: "move details 30"
    input: text
    rows: 3