fields:
  type:
    label: "type"
    input: select
    options:
     Human: Human
     Replicant: Replicant
  imageid:
    label: "imageid"
    input: integer
  archetype:
    label: "archetype"
    input: string
    placeholder: "eg Analyst"
  key memory:
    label: "key memory"
    input: text
    rows: 3
  key relationship:
    label: "key relationship"
    input: text
    rows: 3
  home:
    label: "home"
    input: text
    rows: 3
  appearance:
    label: "appearance"
    input: text
    rows: 3
  notes:
    label: "notes"
    input: text
    rows: 3
  years on the force:
    label: "years on the force"
    input: string
  strength rating:
    label: "strength rating"
    input: select
    options:
      D: D - Febbly (D6)
      C: C - Average (D8)
      B: B - Capable (D10)
      A: A - Extraordinary (D12)
  agility rating:
    label: "agility rating"
    input: select
    options:
      D: D - Febbly (D6)
      C: C - Average (D8)
      B: B - Capable (D10)
      A: A - Extraordinary (D12)
  intelligence rating:
    label: "intelligence rating"
    input: select
    options:
      D: D - Febbly (D6)
      C: C - Average (D8)
      B: B - Capable (D10)
      A: A - Extraordinary (D12)
  empathy rating:
    label: "empathy rating"
    input: select
    options:
      D: D - Febbly (D6)
      C: C - Average (D8)
      B: B - Capable (D10)
      A: A - Extraordinary (D12)
  maneuverability rating:
    label: "maneuverability rating"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  specialties:
    label: "specialties"
    input: text
    rows: 3
  armor name:
    label: "armor name"
    input: string
  armor rating:
    label: "armor rating"
    input: select
    options:
      -: -
      D: D
      C: C
      B: B
      A: A
  armor effect:
    label: "armor effect"
    input: string
  favored gear:
    label: "favored gear"
    input: string
  signature item:
    label: "signature item"
    input: string
  gear:
    label: "gear"
    input: text
    rows: 3
  maximum health:
    label: "maximum health"
    input: string
    placeholder: ""
  current health:
    label: "current health"
    input: string
    placeholder: ""
  critical injuries:
    label: "critical injuries"
    input: string
    placeholder: ""
  maximum resolve:
    label: "maximum resolve"
    input: string
    placeholder: ""
  current resolve:
    label: "current resolve"
    input: string
    placeholder: ""
  critical stress effects:
    label: "critical stress effects"
    input: string
    placeholder: ""
  promotion points:
    label: "promotion points"
    input: string
    placeholder: ""
  humanity points:
    label: "humanity points"
    input: string
    placeholder: ""
  chinyen points:
    label: "chinyen points"
    input: string
  skill name 01:
    label: "skill name 01"
    input: string
  skill rating 01:
    label: "skill rating 01"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 02:
    label: "skill name 02"
    input: string
  skill rating 02:
    label: "skill rating 02"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 03:
    label: "skill name 03"
    input: string
  skill rating 03:
    label: "skill rating 03"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 04:
    label: "skill name 04"
    input: string
  skill rating 04:
    label: "skill rating 04"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 05:
    label: "skill name 05"
    input: string
  skill rating 05:
    label: "skill rating 05"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 06:
    label: "skill name 06"
    input: string
  skill rating 06:
    label: "skill rating 06"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 07:
    label: "skill name 07"
    input: string
  skill rating 07:
    label: "skill rating 07"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 08:
    label: "skill name 08"
    input: string
  skill rating 08:
    label: "skill rating 08"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 09:
    label: "skill name 09"
    input: string
  skill rating 09:
    label: "skill rating 09"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 10:
    label: "skill name 10"
    input: string
  skill rating 10:
    label: "skill rating 10"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 11:
    label: "skill name 11"
    input: string
  skill rating 11:
    label: "skill rating 11"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 12:
    label: "skill name 12"
    input: string
  skill rating 12:
    label: "skill rating 12"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  skill name 13:
    label: "skill name 13"
    input: string
  skill rating 13:
    label: "skill rating 13"
    input: select
    options:
      D: D
      C: C
      B: B
      A: A
  weapon name 01:
    label: "weapon name 01"
    input: string
  weapon dmg 01:
    label: "weapon dmg 01"
    input: string
  weapon crit die 01:
    label: "weapon crit die 01"
    input: select
    options:
      6: D6
      8: D8
      10: D10
      12: D12
  weapon type 01:
    label: "weapon type 01"
    input: string
  weapon min range 01:
    label: "weapon min range 01"
    input: select
    options:
      engaged: engaged
      short: short
      medium: medium
      long: long
      extreme: extreme
  weapon max range 01:
    label: "weapon max range 01"
    input: select
    options:
      engaged: engaged
      short: short
      medium: medium
      long: long
      extreme: extreme
  weapon name 02:
    label: "weapon name 02"
    input: string
  weapon dmg 02:
    label: "weapon dmg 02"
    input: string
  weapon crit die 02:
    label: "weapon crit die 02"
    input: select
    options:
      6: D6
      8: D8
      10: D10
      12: D12
  weapon type 02:
    label: "weapon type 02"
    input: string
  weapon min range 02:
    label: "weapon min range 02"
    input: select
    options:
      engaged: engaged
      short: short
      medium: medium
      long: long
      extreme: extreme
  weapon max range 02:
    label: "weapon max range 02"
    input: select
    options:
      engaged: engaged
      short: short
      medium: medium
      long: long
      extreme: extreme
  weapon name 03:
    label: "weapon name 03"
    input: string
  weapon dmg 03:
    label: "weapon dmg 03"
    input: string
  weapon crit die 03:
    label: "weapon crit die 03"
    input: select
    options:
      6: D6
      8: D8
      10: D10
      12: D12
  weapon type 03:
    label: "weapon type 03"
    input: string
  weapon min range 03:
    label: "weapon min range 03"
    input: select
    options:
      engaged: engaged
      short: short
      medium: medium
      long: long
      extreme: extreme
  weapon max range 03:
    label: "weapon max range 03"
    input: select
    options:
      engaged: engaged
      short: short
      medium: medium
      long: long
      extreme: extreme
