fields:
  name:
    label: "name"
    input: string
  keywords:
    label: "keywords"
    input: string
  level:
    label: "level"
    input: string
  xp:
    label: "xp"
    input: string
  description:
    label: "description"
    input: text
    rows: 3
  imageid:
    label: "imageid"
    input: string
  ctype:
    label: "ctype"
    input: select
    options:
      normal: normal
      mighty: mighty
      legendary: legendary
      notable: notable
      major: major
  body:
    label: "body"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  mind:
    label: "mind"
    input: select
    options:
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      11: 11
      12: 12
  sk melee:
    label: "sk melee"
    input: string
  sk guns:
    label: "sk guns"
    input: string
  sk other:
    label: "sk other"
    input: string
  defense:
    label: "defense"
    input: string
### initiative: body+mind
  health:
    label: "health"
    input: string
  dr physical:
    label: "dr physical"
    input: string
  dr energy:
    label: "dr energy"
    input: string
  dr radiation:
    label: "dr radiation"
    input: string
  dr poison:
    label: "dr poison"
    input: string
  attacks:
    label: "attacks"
    input: text
    rows: 3
  spec abilities:
    label: "spec abilities"
    input: text
    rows: 3
  inventory:
    label: "inventory"
    input: text
    rows: 3